language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get github.com/golang/lint/golint

  # install nsq
  - wget https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz
  - tar xzvf nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz
  - sudo mv nsq-1.0.0-compat.linux-amd64.go1.8/bin/* /bin/ 
  - nsqlookupd &
  - nsqd --lookupd-tcp-address=127.0.0.1:4160 &
  - nsqadmin --lookupd-http-address=127.0.0.1:4161 &
  # install gnatsd & nats-streaming
  - wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.5.0/nats-streaming-server-v0.5.0-linux-amd64.zip
  - unzip -d gnatsd -j nats-streaming-server-v0.5.0-linux-amd64.zip
  - ./gnatsd/nats-streaming-server &

before_script:
  - go vet ./...
  - golint ./...

services:
  - redis

script:
  - go test -v -race ./...
